import { validAttestationNonce, verificationInstructions } from './attestation';
import { McpConfig } from './config';

/**
 * Control-plane client. The MCP adapter is a single operator client of the
 * standard Popcorn API; end users are distinguished by OAuth subject, not by
 * separate Popcorn client credentials.
 */

/** Raw control-plane session (see services/control-plane pool-manager types). */
export type PopcornSession = {
  sessionId: string;
  /** Live view for a human. The control plane returns `url` and `vncUrl`. */
  url?: string;
  vncUrl?: string;
  cdpUrl?: string;
  /** Trusted full-CDP endpoint used only by the MCP agent. */
  cdpInternalUrl?: string;
  expiresAt?: string;
  region?: string;
  [key: string]: unknown;
};

/** Normalized view used by the tool layer. */
export type SessionView = {
  sessionId: string;
  liveViewUrl: string | null;
  agentCdpUrl: string | null;
  expiresAt: string | null;
  region: string | null;
  raw: PopcornSession;
};

export function toSessionView(session: PopcornSession): SessionView {
  return {
    sessionId: session.sessionId,
    liveViewUrl: (session.vncUrl as string) ?? (session.url as string) ?? null,
    // MCP agents need the full DevTools protocol. Never fall back to cdpUrl:
    // that route intentionally applies the public/restricted command policy.
    agentCdpUrl: (session.cdpInternalUrl as string) ?? null,
    expiresAt: (session.expiresAt as string) ?? null,
    region: (session.region as string) ?? null,
    raw: session,
  };
}

export type PopcornResult<T> = { ok: true; data: T } | { ok: false; status: number; error: string };

export type CreateSessionInput = {
  sessionId: string;
  ttlSeconds: number;
  metadata: Record<string, unknown>;
  /** Popcorn region names, ordered nearest-first with later entries as fallback. */
  regions?: string[];
  /** Deployment-managed proxy exit country; callers never provide proxy URLs. */
  proxyCountry?: string;
};

export function createSessionRequestBody(input: CreateSessionInput): Record<string, unknown> {
  return {
    sessionId: input.sessionId,
    ttlSeconds: input.ttlSeconds,
    metadata: input.metadata,
    browserMode: 'normal',
    ...(input.regions ? { regions: input.regions } : {}),
    ...(input.proxyCountry ? { proxy: { country: input.proxyCountry } } : {}),
  };
}

function authHeader(): Record<string, string> {
  return {
    authorization: `Bearer ${McpConfig.controlPlaneClientId}:${McpConfig.controlPlaneClientSecret}`,
    'content-type': 'application/json',
  };
}

async function call<T>(path: string, init: RequestInit): Promise<PopcornResult<T>> {
  const response = await fetch(`${McpConfig.controlPlaneUrl}${path}`, {
    ...init,
    headers: { ...authHeader(), ...(init.headers as Record<string, string> | undefined) },
  });
  const text = await response.text();
  let body: any = {};
  try {
    body = text ? JSON.parse(text) : {};
  } catch {
    body = { error: text };
  }
  if (!response.ok) {
    return { ok: false, status: response.status, error: body?.error ?? `control-plane error ${response.status}` };
  }
  return { ok: true, data: body as T };
}

export function createSession(input: CreateSessionInput): Promise<PopcornResult<PopcornSession>> {
  return call<PopcornSession>('/v1/sessions', {
    method: 'POST',
    body: JSON.stringify(createSessionRequestBody(input)),
  });
}

export function getSession(sessionId: string): Promise<PopcornResult<PopcornSession>> {
  return call<PopcornSession>(`/v1/session/${encodeURIComponent(sessionId)}`, { method: 'GET' });
}

/** The control plane's contract is `extendBySeconds`, not `ttlSeconds`. */
export function extendSession(sessionId: string, extendBySeconds: number): Promise<PopcornResult<PopcornSession>> {
  return call<PopcornSession>(`/v1/session/${encodeURIComponent(sessionId)}/ttl`, {
    method: 'PATCH',
    body: JSON.stringify({ extendBySeconds }),
  });
}

/** Retrieve nonce-bound evidence; cryptographic appraisal requires a separate verifier. */
export async function getSessionAttestation(sessionId: string, nonce: string): Promise<PopcornResult<{ proof: Record<string, unknown>; verification: ReturnType<typeof verificationInstructions> }>> {
  if (!validAttestationNonce(nonce)) return { ok: false, status: 400, error: 'nonce must be 64 lowercase hex characters generated by the caller' };
  try {
    const session = await getSession(sessionId);
    if (!session.ok) return session;
    if (!session.data.cdpInternalUrl) {
      return { ok: false, status: 502, error: 'Session has no runtime gateway URL' };
    }
    const url = new URL(session.data.cdpInternalUrl);
    if (url.protocol !== 'wss:' && url.protocol !== 'ws:') {
      return { ok: false, status: 502, error: 'Invalid runtime gateway protocol' };
    }
    url.protocol = url.protocol === 'wss:' ? 'https:' : 'http:';
    url.username = '';
    url.password = '';
    url.pathname = `/proof/${encodeURIComponent(sessionId)}`;
    url.search = new URLSearchParams({ nonce }).toString();
    url.hash = '';
    // The proof route needs neither operator credentials nor the CDP token.
    const response = await fetch(url, {
      method: 'GET', redirect: 'error', signal: AbortSignal.timeout(65_000),
    });
    if (!response.ok) {
      return { ok: false, status: response.status, error: `Runtime proof request failed (HTTP ${response.status})` };
    }
    const proof = await response.json() as Record<string, any>;
    if (proof?.error || proof?.proof_version !== 'v3' || proof?.nonce !== nonce ||
        typeof proof?.attestation?.token !== 'string' || !proof.attestation.token) {
      return { ok: false, status: 502, error: 'Runtime returned invalid or incomplete attestation evidence' };
    }
    return { ok: true, data: { proof, verification: verificationInstructions(sessionId, nonce, url.origin) } };
  } catch {
    return { ok: false, status: 502, error: 'Runtime attestation request failed or timed out' };
  }
}

export function endSession(sessionId: string): Promise<PopcornResult<Record<string, unknown>>> {
  return call<Record<string, unknown>>(`/v1/session/${encodeURIComponent(sessionId)}`, { method: 'DELETE' });
}
