region: asia-south1
gatewayDomain: ""

externalSecrets:
  enabled: true

secrets:
  browserTurnName: browser-turn-secret

ccDevicePlugin:
  enabled: true

serviceAccount:
  gcpServiceAccount: browser-attestor.iam.gserviceaccount.com

browserRuntimeImage: ghcr.io/reclaimprotocol/popcorn-oss/browser-runtime:latest
browserRuntimeImagePullPolicy: IfNotPresent

browserRuntimeAttestor:
  enabled: true
  imagePullPolicy: IfNotPresent

browserRuntimeAttestorImage: ghcr.io/reclaimprotocol/popcorn-oss/browser-runtime-attestor:latest

extraBrowserRuntimeEnv: []

imagePrepuller:
  enabled: false
  imagePullPolicy: IfNotPresent
  extraInitContainers: []
  extraContainers: []
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 128Mi

webrtc:
  advertiseHost: ""

fleet:
  replicas: 10
  scheduling: Packed
  health:
    initialDelaySeconds: 90
    periodSeconds: 5
    failureThreshold: 6
  browserRuntimeCpuRequest: "1000m"
  browserRuntimeCpuLimit: "2000m"
  browserRuntimeMemoryRequest: 2Gi
  browserRuntimeMemoryLimit: 4Gi
  browserRuntimeAttestorCpuRequest: "100m"
  browserRuntimeAttestorCpuLimit: "200m"
  browserRuntimeAttestorMemoryRequest: 128Mi
  browserRuntimeAttestorMemoryLimit: 256Mi
  extraPorts: []
  extraContainers: []

autoscaler:
  bufferSize: 5
  minReplicas: 10
  maxReplicas: 50
  syncSeconds: 30
