apiVersion: apps/v1
kind: Deployment
metadata:
  name: browser-pool
  labels:
    app: browser-node
spec:
  replicas: 5
  selector:
    matchLabels:
      app: browser-node
  template:
    metadata:
      labels:
        app: browser-node
    spec:
      containers:
      - name: neko
        image: gcr.io/rc-popcorn/browser-node:latest # Production Image
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "3Gi"
            cpu: "2000m"
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: NEKO_SCREEN
          value: "1920x1080@30"
        - name: NEKO_PASSWORD
          value: "neko"
        - name: NEKO_PASSWORD_ADMIN
          value: "admin"
        - name: NEKO_EPR
          value: "52000-52100"
        - name: NEKO_WEBRTC_ICE_UDP_MUX
          value: "true"
        - name: NEKO_NAT1TO1
          value: "34.95.69.141" # Production Gateway IP
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      nodeSelector:
        node_type: standard
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 2Gi
