apiVersion: apps/v1
kind: Deployment
metadata:
  name: popcorn-gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: popcorn/gateway:local
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: popcorn-gateway
spec:
  selector:
    app: gateway
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
