apiVersion: apps/v1
kind: Deployment
metadata:
  name: pool-manager
  labels:
    app: pool-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pool-manager
  template:
    metadata:
      labels:
        app: pool-manager
    spec:
      serviceAccountName: pool-manager
      containers:
      - name: pool-manager
        image: popcorn/pool-manager:local
        imagePullPolicy: Never # Important for local dev without registry
        ports:
        - containerPort: 3000
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: TURN_HOST
          value: "acded8cc7b0c24d2db86f72a32b3271c-1ba1ac6b9da2a8ca.elb.us-east-2.amazonaws.com"
        - name: TURN_SECRET
          value: "popcorn_secret"
        - name: EXTERNAL_ICE_SERVERS_JSON
          value: '[{"urls":"stun:stun.relay.metered.ca:80"},{"urls":"turn:standard.relay.metered.ca:80","username":"d56480eaf09129ab3dff9f46","credential":"mO2dolzJOVmNGy8A"},{"urls":"turn:standard.relay.metered.ca:80?transport=tcp","username":"d56480eaf09129ab3dff9f46","credential":"mO2dolzJOVmNGy8A"},{"urls":"turn:standard.relay.metered.ca:443","username":"d56480eaf09129ab3dff9f46","credential":"mO2dolzJOVmNGy8A"},{"urls":"turns:standard.relay.metered.ca:443?transport=tcp","username":"d56480eaf09129ab3dff9f46","credential":"mO2dolzJOVmNGy8A"}]'
        volumeMounts:
        - name: allocator-client-cert
          mountPath: /etc/agones-allocator-client
          readOnly: true
      volumes:
      - name: allocator-client-cert
        secret:
          secretName: allocator-client.default
---
apiVersion: v1
kind: Service
metadata:
  name: pool-manager
spec:
  selector:
    app: pool-manager
  type: ClusterIP # Internal service only, exposed via Gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
