apiVersion: v1
kind: ServiceAccount
metadata:
  name: pool-manager
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-killer
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pool-manager-pod-killer
  namespace: default
subjects:
- kind: ServiceAccount
  name: pool-manager
  namespace: default
roleRef:
  kind: Role
  name: pod-killer
  apiGroup: rbac.authorization.k8s.io
