{{- if and .Values.metabase.enabled .Values.metabase.domainName .Values.metabase.staticIpName }}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: metabase
spec:
  redirectToHttps:
    enabled: true
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: metabase
spec:
  domains:
    - {{ .Values.metabase.domainName | quote }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metabase
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.metabase.staticIpName | quote }}
    networking.gke.io/managed-certificates: metabase
    networking.gke.io/v1beta1.FrontendConfig: metabase
spec:
  rules:
    - host: {{ .Values.metabase.domainName | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: metabase
                port:
                  number: {{ .Values.metabase.publicServicePort }}
{{- end }}
