{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
data:
  pg_hba.conf: |
    local all all trust
    host all all 127.0.0.1/32 {{ .Values.postgres.hostAuthMethod }}
    host all all ::1/128 {{ .Values.postgres.hostAuthMethod }}
    host all all 0.0.0.0/0 {{ .Values.postgres.hostAuthMethod }}
    host all all ::/0 {{ .Values.postgres.hostAuthMethod }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgres-config
          configMap:
            name: postgres-config
      containers:
        - name: postgres
          image: {{ .Values.postgres.image | quote }}
          imagePullPolicy: {{ .Values.postgres.imagePullPolicy }}
          args:
            - -c
            - hba_file=/var/lib/postgresql/config/pg_hba.conf
            - -c
            - password_encryption=scram-sha-256
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.username | quote }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_INITDB_ARGS
              value: "--auth-host={{ .Values.postgres.hostAuthMethod }} --auth-local=trust"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.existingSecretName }}
                  key: {{ .Values.postgres.passwordSecretKey }}
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-config
              mountPath: /var/lib/postgresql/config
              readOnly: true
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 500m
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: postgres-storage
      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        {{- if .Values.postgres.storageClassName }}
        storageClassName: {{ .Values.postgres.storageClassName | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.postgres.storageSize }}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
{{- end }}
