{{- if .Values.poolManager.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pool-manager
---
{{- end }}
{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway
{{- end }}
{{- $controlPlane := .Values.controlPlane }}
{{- if $controlPlane.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: control-plane-sa
{{- end }}
{{- if .Values.otel.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-agent
{{- end }}
