apiVersion: autoscaling.agones.dev/v1
kind: FleetAutoscaler
metadata:
  name: browser-autoscaler
  namespace: {{ .Release.Namespace }}
spec:
  fleetName: browser-fleet
  policy:
    type: Buffer
    buffer:
      bufferSize: {{ .Values.autoscaler.bufferSize }}
      minReplicas: {{ .Values.autoscaler.minReplicas }}
      maxReplicas: {{ .Values.autoscaler.maxReplicas }}
  sync:
    type: FixedInterval
    fixedInterval:
      seconds: {{ .Values.autoscaler.syncSeconds }}
