{{- if .Values.externalSecrets.enabled }}
{{- $browserRuntimeProxySecret := default "browser-runtime-proxy-secret" .Values.secrets.browserRuntimeProxyName }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $browserRuntimeProxySecret }}
  namespace: {{ .Release.Namespace }}
  finalizers:
    - externalsecrets.external-secrets.io/externalsecret-cleanup
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm
  target:
    name: {{ $browserRuntimeProxySecret }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: HTTPS_PROXY_URL
      remoteRef:
        key: browser-runtime-https-proxy-url
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
